### ISSUE TITLE
And where is jsx-renderer?

### ISSUE THREAD

**Issue by ssleert** [sh4r10/jsx-renderer#1]

**Comment by sh4r10** [comment]
Haven't had time to work on it, but it will be done soon :). Don't understand your interest in it though, its just an educational project for myself, I'm not sure it will be of any use to you.

**Comment by ssleert** [comment]
As example u can check jsx-runtime of my framework https://github.com/valeri-js/valeri/blob/master/src/jsx-runtime/jsx-runtime.js.
